/**
 * licenseManager.cjs — HWID derivation, .lic verification, and online activation.
 *
 * License Flow:
 *   ONLINE:  activateWithKey(key, hwid) → calls Firebase REST API → verifies key is
 *            valid and unbound (or bound to this HWID) → saves cert to local DB.
 *
 *   OFFLINE: verifyLicFile(filePath, hwid) → reads .lic file → verifies RSA-SHA256
 *            signature against embedded public key → checks HWID matches → saves cert.
 *
 * .lic file format (base64-encoded JSON):
 *   {
 *     "payload": { licenseKey, hwid, entitlements, expiresAt, issuedAt },
 *     "signature": "<base64 RSA-SHA256 signature of JSON.stringify(payload)>"
 *   }
 */

"use strict";

const crypto = require("crypto");
const fs = require("fs");
const https = require("https");
const path = require("path");
const getMod = (n) => { try { return require(`./${n}.cjs`); } catch(e) { return require(`./${n}.jsc`); } };
const db = getMod("db");

// ── Embedded RSA-2048 Public Key ─────────────────────────────────────────────
// Generated by the Admin Dashboard. Private key lives only in kencreations-admin/.env
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtIhwxeTMOYDge4XYgKrs
2na1ZcMYsO5aJTi1MoSKLFAoY0a98NNmCDL10D40rW3oHkON+hxjjvUDv51MyR6D
R3lnHx61UdbrknJEcOk45G22R1tIglmSqxmEztrqwWY2UKU+s3thI9bxOovn3C2x
KZADn3tslGadVbjfFFKx3eLe6sgUtLGbrGImPx9yVY5UsgRoTA4kMgPiwsDGqII9
QLqBSYNp8Jsa4zIXiCB1iSmzPL/OfFStlFN67P+XA12nPNowsRERFz2XhvQh6EtL
vmTILonVX2AmB9F76oKOEvRX4mXZE9s+1X2HTvC1GcStEJqjdELDrMFzbLd5EkBH
+wIDAQAB
-----END PUBLIC KEY-----`;

// Firebase project details for the REST API (read-only license lookup)
const FIREBASE_PROJECT_ID = "kencreations-studio";
const FIREBASE_API_KEY = "AIzaSyDLHUB-DGP_pnkOZJijAih3CU7BJB2lwaw";

// ─── HWID Derivation ─────────────────────────────────────────────────────────

/**
 * Returns a stable, one-way hash of the raw machine ID.
 * We never store or transmit the raw ID — only its SHA-256 hash.
 * @param {string} rawMachineId — from node-machine-id machineIdSync()
 * @returns {string} hex string
 */
function deriveHwid(rawMachineId) {
    return crypto
        .createHash("sha256")
        .update("kencreations_hwid_v1:" + rawMachineId)
        .digest("hex");
}

// ─── RSA Signature Verification ──────────────────────────────────────────────

/**
 * Verifies an RSA-SHA256 signature using the embedded public key.
 * @param {string} data      — the exact string that was signed
 * @param {string} signatureB64 — base64-encoded signature
 * @returns {boolean}
 */
function verifySignature(data, signatureB64) {
    try {
        const verify = crypto.createVerify("SHA256");
        verify.update(data);
        return verify.verify(PUBLIC_KEY_PEM.trim(), signatureB64.trim(), "base64");
    } catch (err) {
        console.error("Signature verification error:", err);
        return false;
    }
}

// ─── .lic File Verification (Offline Path) ───────────────────────────────────

/**
 * Loads and verifies an offline .lic file.
 * Returns the verified license payload on success, throws on failure.
 *
 * @param {string} filePath — absolute path to the .lic file chosen by the user
 * @param {string} hwid     — derived HWID of this machine
 * @returns {object} { licenseKey, entitlements, expiresAt, issuedAt }
 */
function verifyLicFile(filePath, hwid) {
    if (!fs.existsSync(filePath)) {
        throw new Error("License file not found.");
    }

    let parsed;
    try {
        const raw = fs.readFileSync(filePath, "utf8");
        parsed = JSON.parse(Buffer.from(raw.trim(), "base64").toString("utf8"));
    } catch {
        throw new Error("Invalid .lic file format. The file may be corrupted.");
    }

    const { payload, signature } = parsed;
    if (!payload || !signature) {
        throw new Error("Malformed .lic file: missing payload or signature.");
    }

    // Verify RSA signature
    const payloadString = JSON.stringify(payload);
    if (!verifySignature(payloadString, signature)) {
        throw new Error(
            "License signature is invalid. This file may have been tampered with.",
        );
    }

    // Verify HWID matches this machine
    if (payload.hwid !== hwid) {
        throw new Error(
            "This license is bound to a different device.\n" +
                "Please contact support to transfer your license.",
        );
    }

    // Verify not expired
    if (payload.expiresAt) {
        const expiry = new Date(payload.expiresAt);
        if (expiry < new Date()) {
            throw new Error(
                "This license has expired. Please contact support to renew.",
            );
        }
    }

    return payload;
}

// ─── Firebase REST Helpers ───────────────────────────────────────────────────

/**
 * Minimal HTTPS GET wrapper that returns parsed JSON.
 * We use raw HTTPS instead of the Firebase SDK to keep the renderer clean.
 * @param {string} url
 * @returns {Promise<any>}
 */
function httpsGet(url) {
    return new Promise((resolve, reject) => {
        const req = https.get(url, (res) => {
            let data = "";
            res.on("data", (chunk) => {
                data += chunk;
            });
            res.on("end", () => {
                try {
                    resolve(JSON.parse(data));
                } catch {
                    reject(new Error("Failed to parse server response."));
                }
            });
        });
        req.on("error", reject);
        req.setTimeout(10000, () => {
            req.destroy();
            reject(new Error("Request timed out."));
        });
    });
}

/**
 * Minimal HTTPS PATCH wrapper for updating Firestore fields.
 * @param {string} url
 * @param {object} body
 * @returns {Promise<any>}
 */
function httpsPatch(url, body) {
    return new Promise((resolve, reject) => {
        const bodyStr = JSON.stringify(body);
        const urlObj = new URL(url);
        const options = {
            hostname: urlObj.hostname,
            path: urlObj.pathname + urlObj.search,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Content-Length": Buffer.byteLength(bodyStr),
            },
        };
        const req = https.request(options, (res) => {
            let data = "";
            res.on("data", (chunk) => {
                data += chunk;
            });
            res.on("end", () => {
                try {
                    resolve(JSON.parse(data));
                } catch {
                    reject(new Error("Failed to parse patch response."));
                }
            });
        });
        req.on("error", reject);
        req.setTimeout(10000, () => {
            req.destroy();
            reject(new Error("Patch request timed out."));
        });
        req.write(bodyStr);
        req.end();
    });
}

/**
 * Reads a Firestore document via the REST API (no auth token required for this path
 * because we use a Firebase custom token issued during online activation for scoped reads).
 *
 * For the initial key-check, we use the public API key with Firestore rules
 * set to allow read of specific fields. A full implementation would use a
 * Firebase Custom Token. For now we use the API key for the initial handshake.
 *
 * @param {string} collection
 * @param {string} documentId
 * @returns {Promise<object|null>}
 */
async function firestoreGet(collection, documentId) {
    const url = `https://firestore.googleapis.com/v1/projects/${FIREBASE_PROJECT_ID}/databases/(default)/documents/${collection}/${encodeURIComponent(documentId)}?key=${FIREBASE_API_KEY}`;
    const result = await httpsGet(url);
    if (result.error) return null;
    return result;
}

/**
 * Converts a Firestore REST API document into a plain JS object.
 * @param {object} fsDoc — raw Firestore REST document
 * @returns {object}
 */
function parseFirestoreDoc(fsDoc) {
    if (!fsDoc || !fsDoc.fields) return null;
    const out = {};
    for (const [key, val] of Object.entries(fsDoc.fields)) {
        if ("stringValue" in val) out[key] = val.stringValue;
        else if ("booleanValue" in val) out[key] = val.booleanValue;
        else if ("integerValue" in val)
            out[key] = parseInt(val.integerValue, 10);
        else if ("timestampValue" in val) out[key] = val.timestampValue;
        else if ("nullValue" in val) out[key] = null;
        else if ("arrayValue" in val) {
            out[key] = (val.arrayValue.values || []).map((v) => {
                if ("stringValue" in v) return v.stringValue;
                return v;
            });
        }
    }
    return out;
}

// ─── Online Activation ───────────────────────────────────────────────────────

/**
 * Activates the app online by verifying the license key against Firestore.
 * On success, writes the verified license state to the local encrypted DB.
 *
 * @param {string} licenseKey — e.g. "KC-7F3A2B"
 * @param {string} hwid       — derived HWID of this machine
 * @returns {Promise<{ success: boolean, message: string, entitlements?: string[] }>}
 */
async function activateWithKey(licenseKey, hwid) {
    try {
        const doc = await firestoreGet("licenses", licenseKey);
        if (!doc) {
            return {
                success: false,
                message: "License key not found. Please check and try again.",
            };
        }

        const data = parseFirestoreDoc(doc);
        if (!data) {
            return {
                success: false,
                message: "Unable to read license data from server.",
            };
        }

        // Check status
        if (data.status === "revoked") {
            return {
                success: false,
                message: "This license has been revoked. Contact support.",
            };
        }
        if (data.status === "expired") {
            return {
                success: false,
                message: "This license has expired. Contact support to renew.",
            };
        }

        // Check expiry date
        if (data.expiresAt) {
            const expiry = new Date(data.expiresAt);
            if (expiry < new Date()) {
                return { success: false, message: "This license has expired." };
            }
        }

        // HWID binding
        if (data.hwid && data.hwid !== hwid) {
            return {
                success: false,
                message:
                    "This license is already bound to another device.\nContact support to reset.",
            };
        }

        // If unbound (type = auto-bind), bind now
        if (!data.hwid) {
            await httpsPatch(
                `https://firestore.googleapis.com/v1/projects/${FIREBASE_PROJECT_ID}/databases/(default)/documents/licenses/${encodeURIComponent(licenseKey)}?key=${FIREBASE_API_KEY}&updateMask.fieldPaths=hwid&updateMask.fieldPaths=hwidBoundAt`,
                {
                    fields: {
                        hwid: { stringValue: hwid },
                        hwidBoundAt: {
                            timestampValue: new Date().toISOString(),
                        },
                    },
                },
            );
        }

        const entitlements = data.entitlements || [];
        const certPayload = {
            licenseKey,
            hwid,
            entitlements,
            issuedAt: new Date().toISOString(),
            expiresAt: data.expiresAt ?? null,
            source: "online",
        };

        // Persist to local encrypted DB
        db.saveLicenseState({
            licenseKey,
            certPayload,
            entitlements,
            expiresAt: data.expiresAt ?? null,
        });

        return {
            success: true,
            message: "License activated successfully!",
            entitlements,
        };
    } catch (err) {
        console.error("[licenseManager] activateWithKey error:", err);
        return {
            success: false,
            message:
                "Could not connect to the license server. Check your internet connection.",
        };
    }
}

// ─── Verify Stored License ───────────────────────────────────────────────────

/**
 * Checks the locally stored license state and returns whether the app is activated.
 * This is the fast-path check used on every startup.
 *
 * @param {string} hwid — derived HWID of this machine
 * @returns {{ activated: boolean, entitlements: string[], reason?: string }}
 */
function checkLocalLicense(hwid) {
    const state = db.getLicenseState();

    if (!state) {
        return { activated: false, entitlements: [], reason: "no_license" };
    }

    if (state.status !== "active") {
        return { activated: false, entitlements: [], reason: "revoked" };
    }

    // Verify cert HWID matches (tamper-check)
    if (state.certPayload && state.certPayload.hwid !== hwid) {
        db.clearLicenseState();
        return { activated: false, entitlements: [], reason: "hwid_mismatch" };
    }

    // Check expiry
    if (state.expiresAt) {
        const expiry = new Date(state.expiresAt);
        if (expiry < new Date()) {
            return {
                activated: false,
                entitlements: state.entitlements,
                reason: "expired",
            };
        }
    }

    return { 
        activated: true, 
        entitlements: state.entitlements,
        plan_type: state.certPayload?.plan_type || 'standard',
        expires_at: state.expiresAt
    };
}

module.exports = {
    deriveHwid,
    verifyLicFile,
    activateWithKey,
    checkLocalLicense,
    firestoreGet,
    parseFirestoreDoc,
};
